### ISSUE TITLE
Set up devnet in CI

### ISSUE THREAD

**Issue by onbjerg** [aragon/node-aragon#5]
We need to run a devnet in a Docker container with WebSocket support. It should also deploy the contracts from aragon/aragon-core.

**Comment by onbjerg** [comment]
We could build an image on top of [Kunstmaan/docker-ethereum](https://github.com/Kunstmaan/docker-ethereum), but with the latest contracts deployed.

Thoughts @izqui?

**Comment by izqui** [comment]
I made this silly image for that yesterday https://hub.docker.com/r/aragon/testgeth/
